# Generated by Django 2.0.2 on 2018-05-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Katale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Katale.ProductType'),
            preserve_default=False,
        ),
    ]
